# These are supported funding model platforms

github: [coolitea]
patreon: coolitea
open_collective: # Replace with a single Open Collective username
ko_fi: coolitea
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
